name: Android RD Client Ubuntu

on:
  workflow_dispatch:
    inputs:
      rdp_password:
        description: 'Set RDP user password'
        required: true
        default: 'P@ssword1234'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Desktop & XRDP
        run: |
          sudo apt update
          sudo DEBIAN_FRONTEND=noninteractive apt install -y xfce4 xfce4-goodies xrdp
          echo xfce4-session > ~/.xsession
          sudo systemctl restart xrdp

      - name: Set Password
        run: |
          echo "runner:${{ github.event.inputs.rdp_password }}" | sudo chpasswd

      - name: Start TCP Tunnel
        run: |
          ssh -p 443 -R0:localhost:3389 -o StrictHostKeyChecking=no -o ServerAliveInterval=30 -N a.pinggy.io > pinggy.log 2>&1 &
          sleep 12
          cat pinggy.log
          echo "================================================="
          echo "Username: runner"
          echo "Password: ${{ github.event.inputs.rdp_password }}"
          echo "================================================="
          sleep 21600
